# -*- coding: utf-8 -*-
"""Relógio Lamport.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1__yhjwFLJpuR82KP-_dYUFSKQ7h89XXO
"""

from threading import Thread
import time

class Relogio_Lamport:
    def __init__(self, processo):
        self.valor = 0
        self.processo = processo

    def incrementar(self):
        self.valor += 1

    def atualizar(self, outro):
        self.valor = max(self.valor, outro) + 1

class Processo(Thread):
    def __init__(self, nome, relogio):
        super().__init__()
        self.nome = nome
        self.relogio = relogio

    def run(self):
        # Simulação de envio de mensagem
        time.sleep(1)
        self.relogio.incrementar()
        print(f"Evento: Processo {self.nome} envia mensagem com relógio {self.relogio.valor}")

        # Simulação de recebimento de mensagem
        time.sleep(1)
        self.relogio.atualizar(3)
        print(f"Evento: Processo {self.nome} recebe mensagem com relógio {self.relogio.valor}")

        # Simulação de resposta
        time.sleep(1)
        self.relogio.incrementar()
        print(f"Evento: Processo {self.nome} envia resposta com relógio {self.relogio.valor}")

def main():
    relogio_p1 = Relogio_Lamport("P1")
    relogio_p2 = Relogio_Lamport("P2")

    processo1 = Processo("P1", relogio_p1)
    processo2 = Processo("P2", relogio_p2)

    processo1.start()
    processo2.start()

    processo1.join()
    processo2.join()

if __name__ == "__main__":
    main()

input()
